version: '3'

services:
  proxy:
    image: traefik
    command: --web --docker --docker.domain=localhost --docker.exposedbydefault=false --logLevel=DEBUG
    networks:
      - webgateway
      - web
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  order:
    build:
      context: order/php-apache
    volumes:
      - ../order:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:order.localhost"
      - "traefik.backend=order"
    networks:
      - webgateway
    restart: always
    depends_on:
      - "logstash"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  user:
    build:
      context: user/php-apache
    volumes:
      - ../user:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:user.localhost"
      - "traefik.backend=user"
    networks:
      - webgateway
    restart: always
    depends_on:
      - "logstash"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  inventory:
    build:
      context: inventory/php-apache
    volumes:
      - ../inventory:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:inventory.localhost"
      - "traefik.backend=inventory"
    networks:
      - webgateway
    restart: always
    depends_on:
      - "logstash"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  api:
    build:
      context: api-gateway/php-apache
    volumes:
      - ../api-gateway:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.localhost"
      - "traefik.backend=api"
    networks:
      - webgateway
    restart: always
    depends_on:
      - "logstash"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    ports:
      - "9200:9200"
    environment:
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - webgateway
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.9
    ports:
      - "5601:5601"
    environment:
      - "xpack.security.enabled=false"
    networks:
      - webgateway
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 10s
      timeout: 5s
      retries: 10

  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.9
    ports:
      - "25826:25826"
    volumes:
      - ../elk-config:/elk-config
    command: logstash -f /elk-config/logstash.config
    networks:
      - webgateway
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local

networks:
  webgateway:
    driver: bridge
  web:
    external:
      name: traefik_webgateway
